/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TOSHIBA
 */
public class Bitth_day_chance extends javax.swing.JFrame {

    double a = 1 ;
    double b = 2 ;
    double c = 3 ;
    double d = 4 ;
    double e = 5 ;
    String secondNumber;
    String result ;
    private Object [] Result;
    public Bitth_day_chance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        see = new javax.swing.JButton();
        jTextdysplay = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextD = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        see.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        see.setText("see");
        see.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeActionPerformed(evt);
            }
        });

        jTextdysplay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextdysplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextdysplayActionPerformed(evt);
            }
        });

        jTextD.setEditable(false);
        jTextD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextD.setToolTipText("result\n");
        jScrollPane2.setViewportView(jTextD);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextdysplay, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(see, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTextdysplay, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(see, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeActionPerformed
        String answer;
        secondNumber = parsedouble(jTextdysplay.getText());
        switch (jTextdysplay.getText()) {
            case "1":
                System.out.println(" u ar giunes");
                answer = String.format("%.of", Result);
                jTextD.setText(answer);
                break;
            case "2":
                System.out.println("u ar nise");
                answer = String.format("%.of", Result);
                jTextD.setText(answer);
                break;
            case "3":
                System.out.println("u ar cule");
                answer = String.format("%.of", Result);
                jTextD.setText(answer);
                break;
            default:
                System.out.println("please inter b/n 1 - 30");
                answer = String .format("%.of",Result);
                jTextD.setText(answer);
                break;
        }
        System.out.prinln( jTextdysplay.getText());
    }//GEN-LAST:event_seeActionPerformed

    private void jTextdysplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextdysplayActionPerformed
        // TODO add your handling code here:
        String Enternumber = jTextdysplay.getText();
        jTextD.setText(Enternumber);
    }//GEN-LAST:event_jTextdysplayActionPerformed

    /**
     * @param args the command line arguments
     */
    public  void main(String args[]) {
        
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextD;
    private javax.swing.JTextField jTextdysplay;
    private javax.swing.JButton see;
    // End of variables declaration//GEN-END:variables

    private Integer parseInteger(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private String parseString(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private String parsedouble(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
